import { Movie } from "../types/Watchlist.types";

export const WATCHLIST_STATIC_DATA: Movie[] = [
   {
      title: "The Shawshank Redemption",
      productionYear: "1994",
      genre: ["Drama"],
      imdbReview: 9.3,
      duration: 142,
      director: "Frank Darabont",
      plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
      cover: "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
   },
   {
      title: "The Godfather",
      productionYear: "1972",
      genre: ["Crime", "Drama"],
      imdbReview: 9.2,
      duration: 267,
      director: "Francis Ford Coppola",
      plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      cover: "https://www.coverwhiz.com/uploads/movies/the-godfather.jpg",
   },
   {
      title: "The Dark Knight",
      productionYear: "2008",
      genre: ["Action", "Crime", "Drama"],
      imdbReview: 9.0,
      duration: 167,
      director: "Christopher Nolan",
      plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept.",
      cover: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.png",
   },
   {
      title: "12 Angry Men",
      productionYear: "1957",
      genre: ["Crime", "Drama"],
      imdbReview: 9.0,
      duration: 96,
      director: "Sidney Lumet",
      plot: "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
      cover: "https://upload.wikimedia.org/wikipedia/commons/b/b5/12_Angry_Men_%281957_film_poster%29.jpg",
   },
   {
      title: "Schindler's List",
      productionYear: "1993",
      genre: ["Biography", "Drama", "History"],
      imdbReview: 9.0,
      duration: 331,
      director: "Steven Spielberg",
      plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their.",
      cover: "https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg",
   },
   {
      title: "The Lord of the Rings: The Return of the King",
      productionYear: "2003",
      genre: ["Action", "Adventure", "Drama"],
      imdbReview: 9.0,
      duration: 315,
      director: "Peter Jackson",
      plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
      cover: "https://m.media-amazon.com/images/I/91UP+jG-ypL.jpg",
   },
   {
      title: "Pulp Fiction",
      productionYear: "1994",
      genre: ["Crime", "Drama"],
      imdbReview: 8.9,
      duration: 123,
      director: "Quentin Tarantino",
      plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      cover: "https://static.posters.cz/image/750/1288.jpg",
   },
   {
      title: "The Good, the Bad and the Ugly",
      productionYear: "1966",
      genre: ["Western"],
      imdbReview: 8.8,
      duration: 432,
      director: "Sergio Leone",
      plot: "A bounty hunting scam joins three men in an uneasy alliance as they search for a fortune buried in a remote cemetery.",
      cover: "https://cdn.europosters.eu/image/750/posters/the-good-the-bad-and-the-ugly-i8932.jpg",
   },
   {
      title: "Fight Club",
      productionYear: "1999",
      genre: ["Drama"],
      imdbReview: 8.8,
      duration: 59,
      director: "David Fincher",
      plot: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
      cover: "https://i.etsystatic.com/18242346/r/il/c9908e/2412674268/il_570xN.2412674268_1sgm.jpg",
   },
];
